export const dummyActivities = [
  {
    id: "4",
    iconSrc: "/icon/activity/plugIcon.svg",
    ready: false,
    type: "photo",
    label: "대기전력 차단하기",
  },
  {
    id: "5",
    iconSrc: "/icon/activity/bagIcon.svg",
    ready: false,
    type: "photo",
    label: "장바구니 사용하기",
  },
  {
    id: "6",
    iconSrc: "/icon/activity/trashIcon.svg",
    ready: false,
    type: "photo",
    label: "분리배출하기",
  },
  {
    id: "7",
    iconSrc: "/icon/activity/stairIcon.svg",
    ready: false,
    type: "photo",
    label: "계단 이용하기",
  },
  {
    id: "8",
    iconSrc: "/icon/activity/leftfoodIcon.svg",
    ready: false,
    type: "photo",
    label: "잔반 없이 먹기",
  },
  {
    id: "9",
    iconSrc: "/icon/activity/busIcon.svg",
    ready: false,
    type: "photo",
    label: "대중교통 이용하기",
  },
  {
    id: "10",
    iconSrc: "/icon/activity/reviewIcon.svg",
    ready: false,
    type: "link",
    label: "친환경 제품 리뷰 남기기",
  },
  {
    id: "11",
    iconSrc: "/icon/activity/bicyleIcon.svg",
    ready: false,
    type: "photo",
    label: "자전거 이용하기",
  },
  {
    id: "12",
    iconSrc: "/icon/activity/billIcon.svg",
    ready: false,
    type: "photo",
    label: "전기/가스 요금 줄이기 챌린지",
  },
  {
    id: "13",
    iconSrc: "/icon/activity/treeIcon.svg",
    ready: false,
    type: "photo",
    label: "가족/커플 나무심기",
  },
];
